name: build the image
on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set image tag from branch
        run: |
          TAG=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          echo "TAG=$TAG" >> $GITHUB_ENV

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/kaniko-action@v1.7.0
        with:
          tags: ghcr.io/guenoledc/blockchain-ops-kata/application:${TAG}
          context: app
          file: app/Dockerfile
          push: true
